name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Setup Python 2.7
      uses: actions/setup-python@v2
      with:
        python-version: '2.7' 
        run: |
          git clone https://github.com/gjhiggins/RDFAlchemy.git
          cd RDFAlchemy
          python setup.py install
    - name: Build with Maven
      run: mvn clean install --projects OLGA-Core,OLGA-Cli --file pom.xml -DskipTests
      working-directory: ./OLGA
