from setuptools import setup, find_packages

setup(
    name='${ontologyName}',
    version='0.0.1a1',
    description='${ontologyName} generated by OLGA',
    packages=find_packages(),
    install_requires=['rdflib', 'RDFAlchemy'],
    author = 'Schneider Electric, DSP, Innovation team',
    python_requires='>=2.7'
)
